general:
steps:
  mtaBuild:
    buildTarget: 'CF'

  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    mtaDeployPlugin:
      dockerImage: 'ppiper/cf-cli'
      
    deployType: 'standard'
    cloudFoundry:
      org: 'P2001760543trial_trial'
      space: 'dev'
      credentialsId: 'ce6f3d8d-4608-4869-9076-e69e9e36e4c4'